# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/mmm-bayes',
                'doc_host': 'https://redam94.github.io',
                'git_url': 'https://github.com/redam94/mmm-bayes',
                'lib_path': 'mmm_bayes'},
  'syms': {'mmm_bayes.core': {'mmm_bayes.core.foo': ('core.html#foo', 'mmm_bayes/core.py')}}}